config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
  # devise signup時のエラー解消
  get 'users' => redirect('/users/sign_up')
  
  # devise password変更時のエラー解消
  get 'users/password' => redirect('users/password/new')
  get 'users/password_reset' => redirect('users/password/edit')
  
  # homes
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  # guest_userとpasswordリセット
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
    patch 'users/password_reset' => 'users/passwords#update', as: 'user_password_reset'
  end
  
  # users
  get 'users/mypage' => 'users#show'
  get 'users/infomation/edit' => 'users#edit'
  get 'users/confirm'
  patch 'users/infomation' => 'users#update'
  delete 'users/infomation' => 'users#destroy'
  
  # recipes
  resources :recipes do
    collection do
      post 'confirm'
      get 'complete'
    end
    resource :recipe_favorites, only: [:create, :destroy]
  end
  
  # recipe_categories
  resources :recipe_categories, only: [:create]
  
  # restaurants
  resources :restaurants do
    collection do
      get 'middle_area_select'
      post 'confirm'
      get 'complete'
    end
    resource :restaurant_favorites, only: [:create, :destroy]
  end
  
  # recipe_categories
  resources :restaurant_genres, only: [:create]
  
  # search
  get 'search' => 'searches#search'
  
  # contacts
  resources :contacts, only: [:new, :create, :index]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :recipe_image
  belongs_to :user
  belongs_to :recipe_category
  has_one :recipe_favorite, dependent: :destroy
  
  validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1},
    presence: true, on: :update
    
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  
  # foodstuff_nameの表記が見やすくなるよう変更
  def foodstuff_name_format
    cleaned_string = foodstuff_name.gsub(/\[|\]|"/, '')
    foodstuff_name_array = cleaned_string.split(', ')
    foodstuff_name_array.join(', ')
  end
  
  # 画像のリサイズ
  def get_recipe_image(width, height)
    unless recipe_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      recipe_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    recipe_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # ユーザーがお気に入りしているか
  def favorited_by?(user)
    !recipe_favorite.nil? && recipe_favorite.user_id == user.id
  end
  
  # キーワード検索
  def self.looks(search, word, user_id)
    if search == "name"
      Recipe.where("name LIKE? AND user_id = ?", "%#{word}%", user_id)
    elsif search == "poster_name"
      Recipe.where("poster_name LIKE? AND user_id = ?", "%#{word}%", user_id)
    elsif search == "cook_time"
      Recipe.where("cook_time LIKE? AND user_id = ?", "%#{word}%", user_id)
    elsif search == "cost"
      Recipe.where("cost LIKE? AND user_id = ?", "%#{word}%", user_id)
    elsif search == "foodstuff_name"
      Recipe.where("foodstuff_name LIKE? AND user_id = ?", "%#{word}%", user_id)
    end
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :ensure_current_user, only: [:show, :edit, :update, :destroy]
  
  def new
    @recipe = Recipe.new
    @recipe_categories = RecipeCategory.all
  end

  def confirm
    @recipe_categories = RecipeCategory.all
    results = []
    
    if params[:recipe][:select_recipe_category_id] == "0"
      category_id = params[:recipe][:recipe_category_id]
    elsif params[:recipe][:select_recipe_category_id] == "1"
      category_id = @recipe_categories.offset( rand(@recipe_categories.count) ).first.category_id
    end
    
    if category_id.blank?
      flash[:alert] = "カテゴリーを選択するか、完全におまかせを選択してください。"
      redirect_to new_recipe_path
    else
      # APIから情報を引き出す
      recipe_category = RecipeCategory.find_by(category_id: category_id)
      RakutenWebService::Recipe.ranking(category_id).each {|n| results << n}
      result = results.sample
      result_hash = {
        user_id: current_user.id,
        recipe_category_id: recipe_category.id,
        name: result["recipeTitle"],
        url: result["recipeUrl"],
        poster_name: result["nickname"],
        cook_time: result["recipeIndication"],
        cost: result["recipeCost"],
        foodstuff_name: result["recipeMaterial"]
      }
      
      # confirm画面ではまだ画像を保存していないため、APIから情報をキープ
      @recipe_image = result["foodImageUrl"]
      
      @recipe = Recipe.new(result_hash)
    end
  end
  
  def create
    recipe = Recipe.new(recipe_params)
    
    # 画像をActiveStrageへ保存
    require 'open-uri'
    recipe_image = params[:recipe][:recipe_image]
    file = URI.open(recipe_image)
    file_name = File.basename(URI.parse(recipe_image).path)
    recipe.recipe_image.attach(io: file, filename: file_name)
    
    recipe.save
    
    # 続けてcomlete画面で情報を表示するため、save情報をsessionに一時保存
    session[:last_saved_info] = recipe
    
    redirect_to complete_recipes_path
  end
  
  def complete
    # 情報表示のための変数代入
    @recipe = session[:last_saved_info]
    @recipe_category = RecipeCategory.find_by(id: @recipe['recipe_category_id'])
    @recipe_info = Recipe.find_by(foodstuff_name: @recipe['foodstuff_name'])
    @foodstuff_name_format = @recipe_info.foodstuff_name_format
  end

  def index
    @recipe_categories = RecipeCategory.all
    @recipe_all = current_user.recipes.all
    recipes = current_user.recipes
    
    # パラメーターでcategory_idかuser_idが渡ってきた際、recipesを上書き
    if params[:category_id]
      if params[:category_id].blank?
        flash[:alert] = "カテゴリーを選択してください。"
        redirect_to recipes_path
      else
        @recipe_category = RecipeCategory.find(params[:category_id])
        @category_recipe_all = @recipe_category.recipes.where(user_id: current_user.id)
        recipes = @recipe_category.recipes.where(user_id: current_user.id)
      end
    elsif params[:user_id]
      favorites = RecipeFavorite.where(user_id: current_user.id).pluck(:recipe_id)
      @favorite_recipe_all = Recipe.where(id: favorites)
      recipes = Recipe.where(id: favorites)
    end
    
    # 順番指定があった際、recipesを上書き
    recipes = params[:latest] ? recipes.latest : recipes
    recipes = params[:old] ? recipes.old : recipes
    recipes = params[:star_count] ? recipes.star_count : recipes
    
    @recipes = recipes.page(params[:page])
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end
  
  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update(recipe_review_params)
      flash[:notice] = "レシピのレビューを変更しました。"
      redirect_to recipe_path(@recipe)
    else
      render "edit"
    end
  end
  
  def destroy
    recipe = current_user.recipes.find(params[:id])
    recipe.destroy
    flash[:notice] = "レシピを削除しました。"
    redirect_to recipes_path
  end
  
  private
  
  def recipe_params
    params.require(:recipe).permit(:user_id, :name, :url, :recipe_category_id, :poster_name, :cook_time, :cost, :foodstuff_name)
  end
  
  # レビュー編集の際のparams
  def recipe_review_params
    params.require(:recipe).permit(:memo, :star)
  end
  
  def ensure_current_user
    if params[:id] == "confirm"
      flash[:alert] = "提案画面でのリロードは無効です。もう一度条件を選択し直してください。"
      redirect_to new_recipe_path
    else
      # 他のユーザーもしくは存在しないレシピを表示させない
      recipe = Recipe.find_by(id: params[:id])
      if recipe.nil? || current_user.id != recipe.user_id
        flash[:alert] = "不正なアクセスです。"
        redirect_to recipes_path
      end
    end
  end
  
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form_rate.html.erb
<div class="form-group d-flex">
  <h2 class="mr-4"><%= f.label :star, "星" %></h2>
  <%= f.hidden_field :star, id: :recipe_star, class: "form-control" %>
  <div id="edit_raty" class="mt-1"></div>
</div>
<script>
  $(document).on('turbolinks:load', function() {
    let editElem = document.querySelector('#edit_raty');
    if (editElem != null) {
      editElem.innerHTML = "";
      let editOpt = {  
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: 'recipe[star]',
        readOnly: false, // 編集時に評価を入力可能にする
        score: <%= recipe.star || 0 %>,
      };
      raty(editElem, editOpt);
    }
  });
</script>

app/views/recipes/_index.html.erb
<div class="row">
  <div class="col-12 d-md-flex">
    <div class="mr-md-auto">
      <% if recipes.present? %>
        <% link_params = {} %>
        <% if params[:category_id] %>
          <% link_params[:category_id] = params[:category_id] %>
        <% elsif params[:user_id] %>
          <% link_params[:user_id] = current_user.id %>
        <% elsif params[:word] %>
          <% link_params[:word] = params[:word] %>
          <% link_params[:range] = "Recipe" %>
          <% link_params[:search] = params[:search] %>
        <% end %>
        <% if params[:word] %>
          <%= link_to "新しい順", search_path(link_params.merge(latest: "true")) %>
          |<%= link_to "古い順", search_path(link_params.merge(old: "true")) %>
          |<%= link_to "評価の高い順", search_path(link_params.merge(star_count: "true")) %>
        <% else %>
          <%= link_to "新しい順", recipes_path(link_params.merge(latest: "true")) %>
          |<%= link_to "古い順", recipes_path(link_params.merge(old: "true")) %>
          |<%= link_to "評価の高い順", recipes_path(link_params.merge(star_count: "true")) %>
        <% end %>
      <% end %>
    </div>
    <% if recipes.present? %>
      <p>【画像提供：楽天レシピ】</p>
    <% end %>
  </div>
</div>
<% unless recipes.present? %>
  <h2 class="text-center mt-5">まだレシピを保存していません。</h2>
  <div class="text-center mt-3">
    <%= link_to "料理を作る", new_recipe_path, class:"btn btn-outline-info" %>
  </div>
<% end %>
<div class="row">
  <% recipes.each do |recipe| %>
    <div class="col-sm-6 col-lg-4 mt-3 px-1">
      <div class="card h-100 border-0">
        <div class="d-inline-block position-relative">
          <%= image_tag recipe.get_recipe_image(500, 500), size: "275x275", class: "w-100 rounded" %>
          <div id="favorite-btn_<%= recipe.id %>" class="d-flex position-absolute favorite">
            <%= render 'recipe_favorites/favorite-btn', recipe: recipe %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to recipe.name, recipe_path(recipe.id), class: "text-dark" %></h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item border-0"><%= recipe.recipe_category.name %></li>
          <li class="list-group-item"><%= render 'recipes/show_rate', recipe: recipe %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="mx-auto mt-3">
    <%= paginate recipes %>
  </div>
</div>

app/views/recipes/_recipe_info.html.erb
<div class="border border-dark p-2 text-center font-weight-bold bg-info">
  <h4 class="my-auto text-white"><%= recipe.name %></h4>
</div>
<div class="border-right border-bottom border-left border-dark">
  <div class="d-md-flex border-bottom">
    <h5 class="my-auto ml-1 font-weight-bold">レシピＵＲＬ:</h5>
    <p class="my-auto ml-2"><a href="<%= recipe.url %>">楽天レシピで詳細を確認する</a></p>
  </div>
  <div class="d-md-flex border-bottom">
    <h5 class="my-auto ml-1  font-weight-bold">カテゴリー名:</h5>
    <p class="my-auto ml-2"><%= recipe.recipe_category.name %></p>
  </div>
  <div class="d-md-flex border-bottom">
    <h5 class="my-auto ml-1 font-weight-bold">レシピ投稿者:</h5>
    <p class="my-auto ml-2"><%= recipe.poster_name %></p>
  </div>
  <div class="d-md-flex border-bottom">
    <h5 class="my-auto ml-1 font-weight-bold">調理時間目安:</h5>
    <p class="my-auto ml-2"><%= recipe.cook_time %></p>
  </div>
  <div class="d-md-flex border-bottom">
    <h5 class="my-auto ml-1 font-weight-bold">材料費の目安:</h5>
    <p class="my-auto ml-2"><%= recipe.cost %></p>
  </div>
  <div class="border-bottom">
    <h5 class="my-auto ml-1 font-weight-bold">材料名の一覧:</h5>
    <p class="my-auto ml-2"><%= recipe.foodstuff_name_format %></p>
  </div>
</div>

app/views/recipes/_show_rate.html.erb
<div id="star_<%= recipe.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= recipe.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= recipe.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/recipes/complete.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-lg-8 text-center mt-5 mx-auto">このレシピに決まりました</h1>
  </div>
  <div class="row">
    <div class="col-lg-4 my-3">
      <div class="text-center">
      <%= image_tag @recipe_info.get_recipe_image(500, 500), size: "275x275", class: "rounded" %>
      </div>
      <p class="text-center">
        【画像提供：楽天レシピ】
      </p>
    </div>
    <div class="col-lg-8 my-3 mx-auto">
      <div class="border border-dark p-2 text-center font-weight-bold bg-info">
        <h4 class="my-auto text-white"><%= @recipe['name'] %></h4>
      </div>
      <div class="border-right border-bottom border-left border-dark">
        <div class="d-md-flex border-bottom">
          <h5 class="my-auto ml-1 font-weight-bold">レシピＵＲＬ:</h5>
          <p class="my-auto ml-2"><a href="<%= @recipe['url'] %>">楽天レシピで詳細を確認する</a></p>
        </div>
        <div class="d-md-flex border-bottom">
          <h5 class="my-auto ml-1 font-weight-bold">カテゴリー名:</h5>
          <p class="my-auto ml-2"><%= @recipe_category.name %></p>
        </div>
        <div class="d-md-flex border-bottom">
          <h5 class="my-auto ml-1 font-weight-bold">レシピ投稿者:</h5>
          <p class="my-auto ml-2"><%= @recipe['poster_name'] %></p>
        </div>
        <div class="d-md-flex border-bottom">
          <h5 class="my-auto ml-1 font-weight-bold">調理時間目安:</h5>
          <p class="my-auto ml-2"><%= @recipe['cook_time'] %></p>
        </div>
        <div class="d-md-flex border-bottom">
          <h5 class="my-auto ml-1 font-weight-bold">材料費の目安:</h5>
          <p class="my-auto ml-2"><%= @recipe['cost'] %></p>
        </div>
        <div class="border-bottom">
          <h5 class="my-auto ml-1 font-weight-bold">材料名の一覧:</h5>
          <p class="my-auto ml-2"><%= @foodstuff_name_format %></p>
        </div>
      </div>
      <div class="text-center pt-5">
        <%= link_to "レビューする", edit_recipe_path(@recipe['id']), class: "btn btn-outline-info" %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/confirm.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-lg-8 text-center mt-5 mx-auto">レシピ提案</h1>
  </div>
  <div class="row">
    <div class="col-lg-4 my-3">
      <div class="text-center">
      <%= image_tag @recipe_image, size: "275x275", class: "rounded" %>
      </div>
      <p class="text-center">
        【画像提供：楽天レシピ】
      </p>
    </div>
    <div class="col-lg-8 my-3 mx-auto">
      <%= render 'recipes/recipe_info', recipe: @recipe %>
      <div class="text-center pt-5">
      <%= form_with model: @recipe, url: recipes_path, method: :post do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :name, :value => @recipe.name %>
        <%= f.hidden_field :url, :value => @recipe.url %>
        <%= f.hidden_field :recipe_category_id, :value => @recipe.recipe_category.id %>
        <%= f.hidden_field :poster_name, :value => @recipe.poster_name %>
        <%= f.hidden_field :cook_time, :value => @recipe.cook_time %>
        <%= f.hidden_field :cost, :value => @recipe.cost %>
        <%= f.hidden_field :foodstuff_name, :value => @recipe.foodstuff_name %>
        <%= f.hidden_field :recipe_image, :value => @recipe_image %>
        <%= f.submit "このレシピにする", class: "btn btn-outline-info" %>
      <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="mt-4 mr-4">
      <%= link_to "条件を変更する", new_recipe_path, class: "btn btn-outline-secondary" %>
    </div>
    <div class="mt-4 mb-4">
      <%= form_with model: @recipe, url: confirm_recipes_path, method: :post do |f| %>
        <%= f.hidden_field :select_recipe_category_id, :value => 0 %>
        <%= f.hidden_field :recipe_category_id, :value => @recipe.recipe_category.category_id %>
        <%= f.submit "同じカテゴリーで再検索", class:"btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <%= render 'layouts/error', error: @recipe %>
  <div class="row">
    <div class="col-12 text-right ml-auto">
      <%= link_to recipe_path(@recipe) do %>
        レシピ詳細へ
        <i class="fa-regular fa-hand-point-right"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <h1 class="col-lg-8 text-center mt-5 mx-auto">レビュー編集</h1>
  </div>
  <div class="row">
    <div class="col-lg-4 my-3">
      <div class="text-center">
      <%= image_tag @recipe.get_recipe_image(500, 500), size: "275x275", class: "rounded" %>
      </div>
      <p class="text-center">
        【画像提供：楽天レシピ】
      </p>
    </div>
    <div class="col-lg-8 my-3 mx-auto">
      <%= render 'recipes/recipe_info', recipe: @recipe %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 my-3 mx-auto">
      <%= form_with model: @recipe, url: recipe_path, method: :patch do |f| %>
        <div class="form-group">
          <h2><%= f.label :memo, "メモ" %></h2>
          <%= f.text_area :memo, placeholder: "ここにメモすることができます。", size: "60x5", class: "w-100" %>
        </div>
        <%= render 'form_rate', f: f, recipe: @recipe %>
        <div class="form-group text-right">
          <%= f.submit "登録する", class: "btn btn-outline-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'searches/recipe_search' %>
    <div class="col-12 text-right ml-auto">
      <% if params[:category_id] || params[:user_id] %>
        <%= link_to recipes_path do %>
          レシピ一覧へ
          <i class="fa-regular fa-hand-point-right"></i>
        <% end %>
      <% else %>
        <%= link_to recipes_path(user_id: current_user.id) do %>
          お気に入り一覧へ
          <i class="fa-regular fa-hand-point-right"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <h1 class="col-lg-8 text-center my-5 mx-auto">
      <% if params[:category_id] %>
        <%= @recipe_category.name %>一覧(全<%= @category_recipe_all.count %>件)
      <% elsif params[:user_id] %>
        お気に入りレシピ一覧(全<%= @favorite_recipe_all.count %>件)
      <% else %>
        作ったレシピ一覧(全<%= @recipe_all.count %>件)
      <% end %>
    </h1>
  </div>
  <%= render 'recipes/index',recipes: @recipes %>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-lg-8 text-center mt-5 mx-auto">料理を作る</h1>
  </div>
  <div class="row">
    <div class="col-md-8 mt-5 mx-auto">
      <%= form_with model: @recipe, url: confirm_recipes_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.radio_button :select_recipe_category_id, 0, checked: true %>
          <%= f.label :recipe_category_id, "カテゴリーを選択する", style: "margin-right:62px;" %>
          <%= f.collection_select :recipe_category_id, @recipe_categories, :category_id, :name, include_blank: "--選択してください--" %>
        </div>
        <div class="form-group">
          <%= f.radio_button :select_recipe_category_id, 1 %>
          <%= f.label :recipe_category_id, "完全にお任せする" %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "まかせてみる", class:"btn btn-outline-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-right ml-auto">
      <%= link_to recipes_path do %>
        レシピ一覧へ
        <i class="fa-regular fa-hand-point-right"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <h1 class="col-lg-8 text-center mt-5 mx-auto">作ったレシピ詳細</h1>
  </div>
  <div class="row">
    <div class="col-lg-4 my-3">
      <div class="text-center">
        <div class="d-inline-block position-relative">
          <%= image_tag @recipe.get_recipe_image(500, 500), size: "275x275", class: "rounded" %>
          <div id="favorite-btn_<%= @recipe.id %>" class="d-flex position-absolute favorite">
            <%= render 'recipe_favorites/favorite-btn', recipe: @recipe %>
          </div>
        </div>
        <p class="text-center">
          【画像提供：楽天レシピ】
        </p>
      </div>
    </div>
    <div class="col-lg-8 my-3 mx-auto">
      <%= render 'recipes/recipe_info', recipe: @recipe %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 my-3 mx-auto">
      <div class="form-group">
        <h2>メモ</h2>
        <%= text_area_tag "memo", @recipe.memo, placeholder: "ここにメモすることができます。", size: "60x5", class: "w-100", readonly: true %>
      </div>
      <div class="form-group d-flex">
        <h2 class="mr-4">星</h2>
        <div class="mt-1"><%= render 'show_rate', recipe: @recipe %></div>
      </div>
      <div class="text-right">
        <%= link_to "編集する", edit_recipe_path(@recipe), class: "btn btn-outline-info mr-4" %>
        <%= link_to "削除する", @recipe, method: :delete, data: { confirm: "このレシピ詳細のデータが消えてしまいます。本当に消しますか？" }, class: "btn btn-outline-danger" %>
      </div>
    </div>
  </div>
</div>