config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
  # devise signup時のエラー解消
  get 'users' => redirect('/users/sign_up')
  
  # devise password変更時のエラー解消
  get 'users/password' => redirect('users/password/new')
  get 'users/password_reset' => redirect('users/password/edit')
  
  # homes
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  # guest_userとpasswordリセット
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
    patch 'users/password_reset' => 'users/passwords#update', as: 'user_password_reset'
  end
  
  # users
  get 'users/mypage' => 'users#show'
  get 'users/infomation/edit' => 'users#edit'
  get 'users/confirm'
  patch 'users/infomation' => 'users#update'
  delete 'users/infomation' => 'users#destroy'
  
  # recipes
  resources :recipes do
    collection do
      post 'confirm'
      get 'complete'
    end
    resource :recipe_favorites, only: [:create, :destroy]
  end
  
  # recipe_categories
  resources :recipe_categories, only: [:create]
  
  # restaurants
  resources :restaurants do
    collection do
      get 'middle_area_select'
      post 'confirm'
      get 'complete'
    end
    resource :restaurant_favorites, only: [:create, :destroy]
  end
  
  # recipe_categories
  resources :restaurant_genres, only: [:create]
  
  # search
  get 'search' => 'searches#search'
  
  # contacts
  resources :contacts, only: [:new, :create, :index]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :recipes, dependent: :destroy
  has_many :restaurants, dependent: :destroy
  has_many :recipe_favorites, dependent: :destroy
  has_many :restaurant_favorites, dependent: :destroy
  
  validates :nickname, presence: true, length: { maximum: 10 }
  validates :email, presence: true, uniqueness: true
  
  # ゲストログインの際、毎回メールアドレス変更（複数人で使える）
  GUEST_USER_PREFIX = "guest_"
  
  def self.guest
    guest_email = "#{GUEST_USER_PREFIX}#{SecureRandom.hex(3)}@example.com"
    find_or_create_by!(email: guest_email) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "guestuser"
    end
  end
    
  def guest_user?
    email.start_with?(GUEST_USER_PREFIX)
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # ゲストログイン
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーでログインしました。"
  end
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit, :confirm]
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def confirm
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "登録情報を変更しました。"
      redirect_to users_mypage_path
    else
      render :edit
    end
  end
  
  def destroy
    user = current_user
    user.destroy
    if user.guest_user?
      flash[:notice] = "ゲストユーザーでログアウトしました。"
    else
      flash[:notice] = "退会処理を実行しました。"
    end
    
    redirect_to root_path
  end
  
  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
  
  def ensure_guest_user
    user = current_user
    if user.guest_user?
      flash[:alert] = "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      redirect_to root_path
    end
  end  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-lg-8 text-center mt-5 mx-auto">本当に退会しますか？</h1>
  </div>
  <div class="row">
    <div class="col-lg-10 mt-5 mx-auto">
      <h3 class="text-center">
        退会すると、会員登録情報や</br>
        これまでの作ったレシピ、食べに行ったお店の</br>
        履歴、レビュー、メモ等全て削除され</br>
        閲覧できなくなります。退会する場合は、</br>
        「退会する」をクリックしてください。
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mt-5 mx-auto text-center mb-3">
      <%= link_to "退会しない", users_mypage_path, class: "btn btn-outline-secondary mr-3" %>
      <%= link_to "退会する", users_infomation_path, method: :delete ,class: "btn btn-outline-danger", data: { confirm: "本当に退会しますか？" } %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <%= render 'layouts/error', error: @user %>
  <div class="row">
    <h1 class="col-lg-8 text-center mt-5 mx-auto">会員情報編集</h1>
  </div>
  <div class="row">
    <div class="col-md-6 mt-5 mx-auto">
      <%= form_with model: @user, url: users_infomation_path, method: :patch do |f| %>
        <div class="d-lg-flex justify-content-between">
          <h4>ニックネーム:</h4>
          <h4><%= f.text_field :nickname %></h4>
        </div>
        <div class="d-lg-flex justify-content-between">
          <h4>メールアドレス:</h4>
          <h4><%= f.text_field :email %></h4>
        </div>
        <div class="text-center my-3">
          <%= f.submit "編集内容を保存", class: "btn btn-outline-secondary" %>
        </div>
        <div class="text-center">
          <%= link_to "退会する", users_confirm_path, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-lg-8 text-center mt-5 mx-auto">マイページ</h1>
  </div>
  <div class="row">
    <div class="col-md-8 mt-5 mx-auto">
      <div class="d-flex mb-3">
      <h2 class="mr-4">登録情報</h2>
      <% unless @user.guest_user? %>
        <%= link_to "編集する", users_infomation_edit_path, class: "btn btn-outline-secondary mb-3" %>
      <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 mx-auto">
      <div class="d-lg-flex justify-content-between">
        <h4>ニックネーム:</h4>
        <h4><%= @user.nickname %></h4>
        <span></span>
      </div>
      <div class="d-lg-flex justify-content-between">
        <h4>メールアドレス:</h4>
        <h4><%= @user.email %></h4>
        <span></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mt-5 mx-auto">
      <div class="d-lg-flex justify-content-between">
        <h2>作ったレシピ&emsp;&emsp;</h2>
        <%= link_to "お気に入り", recipes_path(user_id: current_user.id), class: "btn btn-outline-warning mb-3 mr-5" %>
        <%= link_to "一覧を見る", recipes_path, class: "btn btn-outline-info mb-3 mr-4" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mt-5 mx-auto">
      <div class="d-lg-flex justify-content-between">
        <h2>食べに行ったお店</h2>
        <%= link_to "お気に入り", restaurants_path(user_id: current_user.id), class: "btn btn-outline-warning mb-3 mr-5" %>
        <%= link_to "一覧を見る", restaurants_path, class: "btn btn-outline-info mb-3 mr-4" %>
      </div>
    </div>
  </div>
</div>