config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
  # devise signup時のエラー解消
  get 'users' => redirect('/users/sign_up')
  
  # devise password変更時のエラー解消
  get 'users/password' => redirect('users/password/new')
  get 'users/password_reset' => redirect('users/password/edit')
  
  # homes
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  # guest_userとpasswordリセット
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
    patch 'users/password_reset' => 'users/passwords#update', as: 'user_password_reset'
  end
  
  # users
  get 'users/mypage' => 'users#show'
  get 'users/infomation/edit' => 'users#edit'
  get 'users/confirm'
  patch 'users/infomation' => 'users#update'
  delete 'users/infomation' => 'users#destroy'
  
  # recipes
  resources :recipes do
    collection do
      post 'confirm'
      get 'complete'
    end
    resource :recipe_favorites, only: [:create, :destroy]
  end
  
  # recipe_categories
  resources :recipe_categories, only: [:create]
  
  # restaurants
  resources :restaurants do
    collection do
      get 'middle_area_select'
      post 'confirm'
      get 'complete'
    end
    resource :restaurant_favorites, only: [:create, :destroy]
  end
  
  # recipe_categories
  resources :restaurant_genres, only: [:create]
  
  # search
  get 'search' => 'searches#search'
  
  # contacts
  resources :contacts, only: [:new, :create, :index]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @recipe_categories = RecipeCategory.all
    @restaurant_genres = RestaurantGenre.all
    
    # キーワード検索
    @range = params[:range]
    @word = params[:word]
    @search = params[:search]
    if @range == "Recipe"
      results = Recipe.looks(@search, @word, current_user.id)
    else
      results = Restaurant.looks(@search, @word, current_user.id)
    end
    
    # 順番指定した際のresults
    results = results.latest if params[:latest]
    results = results.old if params[:old]
    results = results.star_count if params[:star_count]
    
    @results = results.page(params[:page])
    @result_all = results.all

    # 検索時の題名用
    if @range == "Recipe"
      search_text_mapping = {
        "name" => "レシピ名",
        "poster_name" => "投稿者名",
        "cook_time" => "調理時間",
        "cost" => "費用",
        "foodstuff_name" => "材料名",
      }
    else
      search_text_mapping = {
        "name" => "店名",
        "address" => "住所",
        "open_time" => "営業時間",
        "legular_holiday" => "定休日",
      }
    end
    
    @search_text = search_text_mapping[@search]
    
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_recipe_search.html.erb
<div class="mr-md-5">
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word, placeholder: "キーワード", size: 15 %>
    <%= f.hidden_field :range, :value => "Recipe" %>
    <%= f.select :search, options_for_select([["レシピ名","name"], ["投稿者名","poster_name"], ["調理時間","cook_time"], ["費用","cost"], ["材料名","foodstuff_name"]]) %>
    <%= button_tag type: "submit", class:"btn btn-default" do %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: @recipe, url: recipes_path, method: :get do |f| %>
    <%= f.collection_select :category_id, @recipe_categories, :id, :name, include_blank: "カテゴリー検索" %>
    <%= button_tag type: "submit", class:"btn btn-default" do %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/_restaurant_search.html.erb
<div class="mr-md-5">
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word, placeholder: "キーワード", size: 15 %>
    <%= f.hidden_field :range, :value => "Restaurant" %>
    <%= f.select :search, options_for_select([["店名","name"], ["住所","address"], ["営業時間","open_time"], ["定休日","legular_holiday"]]) %>
    <%= button_tag type: "submit", class:"btn btn-default" do %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: @restaurant, url: restaurants_path, method: :get do |f| %>
    <%= f.collection_select :genre_id, @restaurant_genres, :id, :name, include_blank: "ジャンル検索" %>
    <%= button_tag type: "submit", class:"btn btn-default" do %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <% if @range == "Recipe" %>
      <%= render 'searches/recipe_search' %>
    <% else %>
      <%= render 'searches/restaurant_search' %>
    <% end %>
    <div class="col-12 text-right ml-auto">
      <% if @range == "Recipe" %>
        <%= link_to recipes_path do %>
          レシピ一覧へ
          <i class="fa-regular fa-hand-point-right"></i>
        <% end %>
      <% else %>
        <%= link_to restaurants_path do %>
          お店一覧へ
          <i class="fa-regular fa-hand-point-right"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <h1 class="col-lg-8 text-center my-5 mx-auto">
      <%= @search_text %> 「<%= @word %>」 の検索結果(全<%= @result_all.count %>件)
    </h1>
  </div>
  <% if @range == "Recipe" %>
      <%= render 'recipes/index', recipes: @results %>
  <% else %>
      <%= render 'restaurants/index', restaurants: @results %>
  <% end %>
</div>