config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
  # devise signup時のエラー解消
  get 'users' => redirect('/users/sign_up')
  
  # devise password変更時のエラー解消
  get 'users/password' => redirect('users/password/new')
  get 'users/password_reset' => redirect('users/password/edit')
  
  # homes
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  # guest_userとpasswordリセット
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
    patch 'users/password_reset' => 'users/passwords#update', as: 'user_password_reset'
  end
  
  # users
  get 'users/mypage' => 'users#show'
  get 'users/infomation/edit' => 'users#edit'
  get 'users/confirm'
  patch 'users/infomation' => 'users#update'
  delete 'users/infomation' => 'users#destroy'
  
  # recipes
  resources :recipes do
    collection do
      post 'confirm'
      get 'complete'
    end
    resource :recipe_favorites, only: [:create, :destroy]
  end
  
  # recipe_categories
  resources :recipe_categories, only: [:create]
  
  # restaurants
  resources :restaurants do
    collection do
      get 'middle_area_select'
      post 'confirm'
      get 'complete'
    end
    resource :restaurant_favorites, only: [:create, :destroy]
  end
  
  # recipe_categories
  resources :restaurant_genres, only: [:create]
  
  # search
  get 'search' => 'searches#search'
  
  # contacts
  resources :contacts, only: [:new, :create, :index]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error.html.erb
<% if error.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= error.errors.count %>件のエラーが発生しました
    </h6>
    <% error.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<div class="d-md-flex justify-content-center">
  <!-- Rakuten logo -->
  <div class="mt-3 text-center">
    <a href="https://webservice.rakuten.co.jp/" target="_blank">
      <img src="https://webservice.rakuten.co.jp/img/credit/200709/credit_31130.gif" border="0" alt="Rakuten Web Service Center" title="Rakuten Web Service Center" width="311" height="30"/>
    </a>
  </div>
  <!-- Hot Pepper logo -->
  <div class="mt-3 text-center">
    <a href="http://webservice.recruit.co.jp/">
      <img src="http://webservice.recruit.co.jp/banner/hotpepper-m.gif" alt="ホットペッパー Webサービス" width="88" height="35" border="0" title="ホットペッパー Webサービス">
    </a>
  </div>
</div>
<p class="text-center mt-3">
  <small>©CopyRight Makasete-Meal.inc</small>
</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "MakaseteMeal_logo.png", alt: "Makasete Meal" %>
    <% end %>
    <% if user_signed_in? %>
      <p class="pt-3 ml-md-5">ようこそ、<%= current_user.nickname %>さん</p>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "btn btn-light nav-link ml-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "お問い合わせ", new_contact_path, class: "btn btn-light nav-link ml-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", users_mypage_path, class: "btn btn-light nav-link ml-2" %>
          </li>
          <li class="nav-item">
            <% if current_user.guest_user? %>
              <%= link_to "ログアウト", users_infomation_path, method: :delete, class: "btn btn-light nav-link ml-2" %>
            <% else %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-light nav-link ml-2" %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "btn btn-light nav-link ml-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "btn btn-light nav-link ml-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-light nav-link ml-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-light nav-link ml-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Makasete Meal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/<%= ENV['FontAwesome_KEY'] %>.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="border-bottom">
      <%= render 'layouts/header' %>
    </header>
    <div class="container px-5 px-sm-0">
      <div class="row">
        <div class="col-md-8 mt-2 mx-auto text-center">
          <% if flash[:notice] %>
            <div class="alert alert-success">
              <%= flash[:notice] %>
            </div>
          <% elsif flash[:alert] %>
            <div class="alert alert-danger">
              <%= flash[:alert] %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="border-top">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>